spring:
  application:
    name: iltuo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    open-in-view: false
    #show-sql: true
    show-sql: false
    # properties:
      # hibernate:
        # format_sql: true
        # use_sql_comments: true
        # highlight_sql: true
        # type: trace
        # jdbc:
          # batch_size: 30
          # generate_statistics: true
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${OAUTH_NAVER_CLIENT_ID}
            client-secret: ${OAUTH_NAVER_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/api/v1/auth/social/callback/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
              - mobile
          kakao:
            client-id: ${OAUTH_KAKAO_CLIENT_ID}
            client-secret: ${OAUTH_KAKAO_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/api/v1/auth/social/callback/{registrationId}"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              profile_nickname
          google:
            client-id: ${OAUTH_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH_GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/api/v1/auth/social/callback/{registrationId}"
            scope:
              - profile
              - email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
# logging:
  # level:
    # org.hibernate.orm.jdbc.bind: trace
jwt:
  access:
    secret: ${JWT_ACCESS_SECRET}
    expiration: 300000
  refresh:
    secret: ${JWT_REFRESH_SECRET}
    expiration: 604920000
file:
  upload-dir: ${FILE_UPLOAD_PATH}
server:
  port: 4000